repos:
  - repo: local
    hooks:
      - id: pytest
        name: run pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false

      - id: isort
        name: run isort
        entry: isort
        language: system
        types: [python]
        pass_filenames: true

      - id: flake8
        name: run flake8
        entry: flake8
        language: system
        types: [python]
        pass_filenames: true